---
title: "Bivariate Normal Distribution"
author: "Stefan Britz"
date: "University of Cape Town"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, warning=FALSE}
library(rgl)
library(mvtnorm)
library(htmlwidgets)
```



### Change the values of the $\sigma^2_X$, $\sigma^2_Y$ and $\rho_{XY}$ to see how the joint probability density function of a Bivariate Gaussian distribution changes



```{r, echo=FALSE}
inputPanel(
  sliderInput("varx", label = "Var(X)",
              min = 0.1, max = 5, value = 1, step = 0.1),
  
  sliderInput("vary", label = "Var(Y)",
              min = 0.1, max = 5, value = 1, step = 0.1),
  
  sliderInput("rho", label = 'Correlation Coefficient',
              min = -1, max = 1, value = 0, step = 0.1),
  
  radioButtons("fix", label = 'Fix vertical axis scale?', choices = c("Yes" = "y", "No" = "n"), inline = TRUE),
  
  checkboxInput("topview", "View from above", FALSE)
)
```





```{r echo=FALSE, warning=FALSE}

myRenderRglwidget <- function(expr, env = parent.frame(), quoted = FALSE, outputArgs = list()) {
  if (!quoted) expr <- substitute(expr) # force quoted
  
  markRenderFunction(rglwidgetOutput,
                     shinyRenderWidget(expr, rglwidgetOutput, env, quoted = TRUE),
                     outputArgs = outputArgs)
}

options(rgl.useNULL=TRUE)
myRenderRglwidget({
  
  x <- seq(-4, 4, 0.05)
  y <- seq(-4, 4, 0.05)
  f <- dmvnorm(expand.grid(x, y), mean = c(0,0), sigma = matrix(c(input$varx, 
                                                                  input$rho*sqrt(input$varx)*sqrt(input$vary), 
                                                                  input$rho*sqrt(input$varx)*sqrt(input$vary), 
                                                                  input$vary), 
                                                                2, 2))
  
  try(rgl.close())
  
  nbcol <- 150
  colour <- rev(rainbow(nbcol, start = 0, end = 0.7))
  fcol <- cut(f, nbcol)
  ifelse(input$fix == "y",
         persp3d(x, y, f, col = colour[fcol], xlab = 'X', ylab = 'Y', zlab = 'f(x, y)', zlim = c(0, 0.35), box = TRUE),
         persp3d(x, y, f, col = colour[fcol], xlab = 'X', ylab = 'Y', zlab = 'f(x, y)', box = FALSE)
  )
  
  if(input$topview) rgl.viewpoint(0, 0)
  if(!input$topview) rgl.viewpoint(0, -45) #ifelse gives "replacement has length zero" error for some reason
  par3d(zoom = 0.75)
  
  rglwidget()
  
}, outputArgs = list(width = 800, height = 600))

```


